language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
env:
  matrix:
     - DJANGO_VERSION="Django<1.8"
     - DJANGO_VERSION="Django<1.9"
     - DJANGO_VERSION="Django<1.10"
     - DJANGO_VERSION="Django<1.11"
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install "$DJANGO_VERSION"  "coverage==3.7.1" coveralls "mock>=1.0.1"
matrix:
  exclude:
    # Django 1.9+ no longer supports python 3.3
    - python: "3.5"
      env: DJANGO_VERSION="Django<1.8"
    - python: "3.6"
      env: DJANGO_VERSION="Django<1.8"
    - python: "3.3"
      env: DJANGO_VERSION="Django<1.10"
    - python: "3.3"
      env: DJANGO_VERSION="Django<1.11"
# command to run tests
script:
  - python manage.py test
  - coverage run manage.py test notifyAll
after_success:
  - coverage report
  - coveralls